#!/usr/bin/env python3
"""
Telegram Alert Bot
===================
Sends daily stock picks and market summary to a Telegram channel/group.

Setup:
  1. Create a bot via @BotFather on Telegram
  2. Get the bot token
  3. Add bot to your channel/group
  4. Get the chat_id (use @userinfobot or /getUpdates API)
  5. Set environment variables:
     export TELEGRAM_BOT_TOKEN="your-bot-token"
     export TELEGRAM_CHAT_ID="your-chat-id"

Usage:
  python scripts/telegram_alerts.py --run-dir runs/2026-03-12
  python scripts/telegram_alerts.py --run-dir runs/2026-03-12 --top 10
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from datetime import date
from pathlib import Path
from typing import List, Optional
from urllib.parse import quote

sys.path.insert(0, str(Path(__file__).parent.parent))


def format_score_emoji(score: Optional[float]) -> str:
    if score is None:
        return "⬜"
    if score >= 70:
        return "🟢"
    if score >= 50:
        return "🟡"
    return "🔴"


def format_recommendation_emoji(rec: str) -> str:
    return {
        "Buy": "🟢 Buy",
        "Hold": "🟡 Hold",
        "Avoid": "🔴 Avoid",
        "Watch": "👁 Watch",
    }.get(rec, f"⬜ {rec}")


def build_daily_message(run_dir: Path, top_n: int = 10) -> str:
    """Build the daily summary message."""
    run_date = run_dir.name

    # Load run log
    run_log = {}
    rl_path = run_dir / "run_log.json"
    if rl_path.exists():
        try:
            run_log = json.loads(rl_path.read_text())
        except json.JSONDecodeError:
            pass

    # Load stocks
    stocks = []
    for sf in sorted(run_dir.glob("stock_*.json")):
        try:
            data = json.loads(sf.read_text())
            if data.get("investability_gate_passed"):
                stocks.append(data)
        except (json.JSONDecodeError, IOError):
            continue

    # Sort by selection score
    stocks.sort(key=lambda s: s.get("selection_score") or s.get("final_opportunity_score") or 0, reverse=True)

    # Build message
    lines = []
    lines.append(f"📊 *NSE Screener — Daily Report*")
    lines.append(f"📅 *Date:* {run_date}")

    market_mode = run_log.get("market_mode", "neutral")
    lines.append(f"📈 *Market Mode:* {market_mode.title()}")
    lines.append(f"🔢 *Universe:* {run_log.get('universe_size', '—')} stocks")
    lines.append("")

    buy_stocks = [s for s in stocks if s.get("recommendation") == "Buy"]
    lines.append(f"✅ *Buy Candidates:* {len(buy_stocks)}")
    lines.append("")

    if buy_stocks:
        lines.append("🏆 *Top Picks:*")
        lines.append("")

        for i, stock in enumerate(buy_stocks[:top_n], 1):
            ticker = stock.get("ticker", "?")
            name = stock.get("stock_name", ticker)
            score = stock.get("final_opportunity_score", 0)
            entry = stock.get("entry_signal", "—")
            upside = stock.get("expected_upside_pct")
            rr = stock.get("risk_reward_ratio")

            cards = stock.get("cards", {})
            perf = cards.get("performance", {}).get("score")
            val = cards.get("valuation", {}).get("score")
            growth = cards.get("growth", {}).get("score")

            lines.append(f"*{i}\\. {_escape_md(ticker)}* — {_escape_md(name[:30])}")
            lines.append(f"   Score: *{score:.1f}* | Entry: {_escape_md(entry)}")

            if upside is not None:
                lines.append(f"   Upside: {upside:.1f}%", )
            if rr is not None:
                lines.append(f"   R/R: {rr:.2f}")

            emoji_line = (
                f"   {format_score_emoji(perf)} Perf "
                f"{format_score_emoji(val)} Val "
                f"{format_score_emoji(growth)} Growth"
            )
            lines.append(emoji_line)

            thesis = stock.get("thesis", "")
            if thesis:
                # Truncate thesis for Telegram
                short_thesis = thesis[:200] + "..." if len(thesis) > 200 else thesis
                lines.append(f"   _{_escape_md(short_thesis)}_")
            lines.append("")

    else:
        lines.append("_No stocks meet Buy criteria today\\._")
        lines.append("")

    # Sector summary
    if buy_stocks:
        sectors = {}
        for s in buy_stocks:
            sect = s.get("classification", {}).get("sector", "Other")
            sectors[sect] = sectors.get(sect, 0) + 1

        if sectors:
            lines.append("📊 *Sector Breakdown:*")
            for sect, count in sorted(sectors.items(), key=lambda x: -x[1]):
                lines.append(f"  • {_escape_md(sect)}: {count}")
            lines.append("")

    lines.append("_Generated by NSE Screener Engine V2_")

    return "\n".join(lines)


def _escape_md(text: str) -> str:
    """Escape special characters for Telegram MarkdownV2."""
    special = ['_', '*', '[', ']', '(', ')', '~', '`', '>', '#', '+', '-', '=', '|', '{', '}', '.', '!']
    for ch in special:
        text = text.replace(ch, f'\\{ch}')
    return text


def build_plain_message(run_dir: Path, top_n: int = 10) -> str:
    """Build plain text version (for HTML parse mode)."""
    run_date = run_dir.name

    run_log = {}
    rl_path = run_dir / "run_log.json"
    if rl_path.exists():
        try:
            run_log = json.loads(rl_path.read_text())
        except json.JSONDecodeError:
            pass

    stocks = []
    for sf in sorted(run_dir.glob("stock_*.json")):
        try:
            data = json.loads(sf.read_text())
            if data.get("investability_gate_passed"):
                stocks.append(data)
        except (json.JSONDecodeError, IOError):
            continue

    stocks.sort(key=lambda s: s.get("selection_score") or s.get("final_opportunity_score") or 0, reverse=True)

    lines = []
    lines.append(f"<b>📊 NSE Screener — Daily Report</b>")
    lines.append(f"📅 Date: {run_date}")
    lines.append(f"📈 Market: {run_log.get('market_mode', 'neutral').title()}")
    lines.append("")

    buy_stocks = [s for s in stocks if s.get("recommendation") == "Buy"]
    lines.append(f"✅ <b>Buy Candidates: {len(buy_stocks)}</b>")
    lines.append("")

    for i, stock in enumerate(buy_stocks[:top_n], 1):
        ticker = stock.get("ticker", "?")
        score = stock.get("final_opportunity_score", 0)
        entry = stock.get("entry_signal", "—")
        upside = stock.get("expected_upside_pct")

        upside_str = f" | ↑{upside:.1f}%" if upside else ""
        lines.append(f"<b>{i}. {ticker}</b> — Score: {score:.1f}{upside_str}")
        lines.append(f"   Entry: {entry}")

        thesis = stock.get("thesis", "")
        if thesis:
            short = thesis[:150] + "..." if len(thesis) > 150 else thesis
            lines.append(f"   <i>{short}</i>")
        lines.append("")

    lines.append("<i>Generated by NSE Screener V2</i>")
    return "\n".join(lines)


def send_telegram_message(
    message: str,
    bot_token: str,
    chat_id: str,
    parse_mode: str = "HTML",
) -> bool:
    """Send a message via Telegram Bot API."""
    import requests

    url = f"https://api.telegram.org/bot{bot_token}/sendMessage"
    payload = {
        "chat_id": chat_id,
        "text": message,
        "parse_mode": parse_mode,
        "disable_web_page_preview": True,
    }

    try:
        resp = requests.post(url, json=payload, timeout=30)
        if resp.status_code == 200:
            return True
        else:
            print(f"[Telegram] Error {resp.status_code}: {resp.text}")
            return False
    except Exception as e:
        print(f"[Telegram] Send failed: {e}")
        return False


def parse_args():
    parser = argparse.ArgumentParser(description="Send Telegram alerts")
    parser.add_argument("--run-dir", required=True, help="Path to run directory")
    parser.add_argument("--top", type=int, default=10, help="Top N picks to include")
    parser.add_argument("--dry-run", action="store_true", help="Print message without sending")
    parser.add_argument("--bot-token", default=None, help="Telegram bot token (or TELEGRAM_BOT_TOKEN env)")
    parser.add_argument("--chat-id", default=None, help="Telegram chat ID (or TELEGRAM_CHAT_ID env)")
    return parser.parse_args()


def main():
    args = parse_args()
    run_dir = Path(args.run_dir)

    if not run_dir.exists():
        print(f"Run directory not found: {run_dir}")
        sys.exit(1)

    # Build message (use HTML mode for reliability)
    message = build_plain_message(run_dir, args.top)

    if args.dry_run:
        print("[Telegram] DRY RUN — Message preview:")
        print("=" * 60)
        # Strip HTML for preview
        import re
        clean = re.sub(r'<[^>]+>', '', message)
        print(clean)
        print("=" * 60)
        print(f"[Message length: {len(message)} chars]")
        return

    bot_token = args.bot_token or os.environ.get("TELEGRAM_BOT_TOKEN")
    chat_id = args.chat_id or os.environ.get("TELEGRAM_CHAT_ID")

    if not bot_token or not chat_id:
        print("[Telegram] Missing credentials. Set TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID env vars.")
        print("  Or use --bot-token and --chat-id flags.")
        print("\nMessage preview:")
        import re
        clean = re.sub(r'<[^>]+>', '', message)
        print(clean)
        sys.exit(1)

    # Split long messages (Telegram limit: 4096 chars)
    if len(message) > 4000:
        chunks = [message[i:i+4000] for i in range(0, len(message), 4000)]
    else:
        chunks = [message]

    for i, chunk in enumerate(chunks):
        success = send_telegram_message(chunk, bot_token, chat_id, "HTML")
        if success:
            print(f"[Telegram] Sent part {i+1}/{len(chunks)}")
        else:
            print(f"[Telegram] Failed to send part {i+1}/{len(chunks)}")
            sys.exit(1)

    print("[Telegram] All messages sent successfully!")


if __name__ == "__main__":
    main()
